/** @type {import('tailwindcss').Config} */
const colors = require('tailwindcss/colors');

module.exports = {
    content: [
        './index.html',
        './src/**/*.{vue,js,ts,jsx,tsx}',
    ],
    options: {
        safelist: ['html', 'body'],
    },
    theme: {
        extend: {
            colors: {
                primary: {
                    50: '#EFF6FF',
                    '50-contrast': colors.gray[900],
                    100: '#DBEAFE',
                    '100-contrast': colors.gray[900],
                    200: '#BFDBFE',
                    '200-contrast': colors.gray[900],
                    300: '#93C5FD',
                    '300-contrast': colors.gray[900],
                    400: '#60A5FA',
                    '400-contrast': colors.white,
                    500: '#3B82F6',
                    '500-contrast': colors.white,
                    600: '#2563EB',
                    '600-contrast': colors.white,
                    700: '#1D4ED8',
                    '700-contrast': colors.white,
                    800: '#1E40AF',
                    '800-contrast': colors.white,
                    900: '#1E3A8A',
                    '900-contrast': colors.white,
                },
                secondary: {
                    50: '#F5F3FF',
                    '50-contrast': colors.gray[900],
                    100: '#EDE9FE',
                    '100-contrast': colors.gray[900],
                    200: '#DDD6FE',
                    '200-contrast': colors.gray[900],
                    300: '#C4B5FD',
                    '300-contrast': colors.gray[900],
                    400: '#A78BFA',
                    '400-contrast': colors.white,
                    500: '#8B5CF6',
                    '500-contrast': colors.white,
                    600: '#7C3AED',
                    '600-contrast': colors.white,
                    700: '#6D28D9',
                    '700-contrast': colors.white,
                    800: '#5B21B6',
                    '800-contrast': colors.white,
                    900: '#4C1D95',
                    '900-contrast': colors.white,
                },
                danger: {
                    50: colors.red[50],
                    '50-contrast': colors.gray[900],
                    100: colors.red[100],
                    '100-contrast': colors.gray[900],
                    200: colors.red[200],
                    '200-contrast': colors.gray[900],
                    300: colors.red[300],
                    '300-contrast': colors.gray[900],
                    400: colors.red[400],
                    '400-contrast': colors.white,
                    500: colors.red[500],
                    '500-contrast': colors.white,
                    600: colors.red[600],
                    '600-contrast': colors.white,
                    700: colors.red[700],
                    '700-contrast': colors.white,
                    800: colors.red[800],
                    '800-contrast': colors.white,
                    900: colors.red[900],
                    '900-contrast': colors.white,
                },
                warning: {
                    50: colors.amber[50],
                    '50-contrast': colors.gray[900],
                    100: colors.amber[100],
                    '100-contrast': colors.gray[900],
                    200: colors.amber[200],
                    '200-contrast': colors.gray[900],
                    300: colors.amber[300],
                    '300-contrast': colors.gray[900],
                    400: colors.amber[400],
                    '400-contrast': colors.white,
                    500: colors.amber[500],
                    '500-contrast': colors.white,
                    600: colors.amber[600],
                    '600-contrast': colors.white,
                    700: colors.amber[700],
                    '700-contrast': colors.white,
                    800: colors.amber[800],
                    '800-contrast': colors.white,
                    900: colors.amber[900],
                    '900-contrast': colors.white,
                },
                success: {
                    50: colors.green[50],
                    '50-contrast': colors.gray[900],
                    100: colors.green[100],
                    '100-contrast': colors.gray[900],
                    200: colors.green[200],
                    '200-contrast': colors.gray[900],
                    300: colors.green[300],
                    '300-contrast': colors.gray[900],
                    400: colors.green[400],
                    '400-contrast': colors.white,
                    500: colors.green[500],
                    '500-contrast': colors.white,
                    600: colors.green[600],
                    '600-contrast': colors.white,
                    700: colors.green[700],
                    '700-contrast': colors.white,
                    800: colors.green[800],
                    '800-contrast': colors.white,
                    900: colors.green[900],
                    '900-contrast': colors.white,
                },
            },
        },
    },
};
